app = "manhwa-notifier-api"
primary_region = "iad"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"

[[services]]
  http_checks = []
  internal_port = 5000
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 100
    soft_limit = 80
    type = "connections"
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
  [services.tcp_checks]
    interval = "15s"
    timeout = "2s"

[[checks]]
  name = "health"
  type = "http"
  interval = "30s"
  timeout = "5s"
  path = "/api/health"


