app = "manhwa-notifier-api"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"

[[checks]]
  name = "health"
  type = "http"
  interval = "30s"
  timeout = "5s"
  path = "/api/health"


